# parameters.yaml
# Global configuration for ONOS-GNN-PPO framework
# Used for reproducible experiments and automated runs.

general:
  project_name: "ONOS-GNN-PPO for Healthcare IoT"
  seed: 42
  dataset: "H-CIoT"
  controller: "ONOS v2.6"
  emulation_platform: "Mininet 2.3.0"
  gpu: "NVIDIA RTX 3090"
  cpu: "Intel Core i9"

gnn:
  input_dim: 16
  hidden_dim: 64
  output_dim: 64
  layers: 2
  activation: "relu"
  learning_rate: 0.001

ppo:
  actor_lr: 0.0003
  critic_lr: 0.0003
  gamma: 0.99
  clip_epsilon: 0.2
  update_epochs: 4
  batch_size: 64
  entropy_coeff: 0.01
  lambda1_latency_weight: 0.4
  lambda2_energy_weight: 0.3
  lambda3_attack_weight: 0.2

federated_learning:
  num_clients: 5
  rounds: 10
  local_epochs: 2
  aggregation: "FedAvg"
  defense: "Krum"
  privacy_preserving: true

energy_model:
  alpha_cpu: 0.4
  beta_memory: 0.35
  gamma_tx: 0.25

evaluation:
  metrics: ["throughput", "latency", "energy", "auc", "cpu_usage"]
  topologies: ["GEANT", "NSFNET", "FatTree"]
  repetitions: 10
  confidence_interval: 0.95

logging:
  save_results: true
  output_dir: "results/"
  checkpoint_dir: "checkpoints/"
  print_frequency: 50
